### PR TITLE
fix: node-ipc

### PR DESCRIPTION
**Pull request by atian25**
https://github.com/RIAEvangelist/node-ipc/issues/233

### CODE REVIEW

**Comment by gemwuu** [comment]
LGTM

**Review by gemwuu — APPROVED** [review]

**Comment by atian25** [comment]
image

**Comment by hax** [comment]
有鉴于此模块的有意行为（包括更恶劣的根据IP覆盖文件），光针对特定版本可能还不够，可能需要暂时直接锁定后续所有版本。

**Comment by fengmk2** [comment]
> 有鉴于此模块的有意行为（包括更恶劣的根据IP覆盖文件），光针对特定版本可能还不够，可能需要暂时直接锁定后续所有版本。

我会先锁定 node-ipc 的更新同步

**Comment by atian25** [comment]
@fengmk2  是不是顺便把这 3 个版本先手动删掉？

新版 cnpm registry 好像没有迁移这个：https://github.com/cnpm/cnpmcore/issues/184

**Comment by hax** [comment]
Copy from https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068752723

The behavior — committed malicious code, deleted comments which expose such code, revoked the api key after been exposed and promoted the sophistry that the code not work because api key is not valid — make me think the guy is not worth trust anymore. I strongly suggest npmmirror not only blacklist node-ipc but all his packages.

**Comment by atian25** [comment]
https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

**Comment by SekiBetu** [comment]
好吓人啊

**Pull request merged**
