### PR TITLE
feat: fix unexpected breakages which 8.14.0 security release introduced

### PR DESCRIPTION
**Pull request by hyj1991**
Detail: https://github.com/nodejs/node/pull/24811

### CODE REVIEW

**Comment by fengmk2** [comment]
landed 42d7bee4e38836bde0860e483988b28aba42e998

**Comment by fengmk2** [comment]
@hyj1991 我将其他 node 版本也升级了。

**Comment by fengmk2** [comment]
1.23.0

**Comment by hyj1991** [comment]
ok

**Pull request closed without merging**
